#Eureka Server PORT
server:
  port: 8761

#Spring Cloud ID
spring:
  application:
    name: discoveryService

#Server?? ???
eureka:
  client:
    register-with-eureka: false  #Eureka ????? ?????? ??? ????? ???? ???.
    fetch-registry: false
